#pragma once

#include <cstdint>

namespace DSP {

/**
 * @brief Unique identifiers for all built-in DSP node types.
 */
enum NodeType : uint32_t {
    NODE_TYPE_INVALID = 0,
    NODE_TYPE_CHANNEL_STRIP = 1000,
    NODE_TYPE_PANNER = 1001,
    NODE_TYPE_SAMPLER = 1002,
    NODE_TYPE_INSERT_PLUGIN = 1003,
    NODE_TYPE_BUS = 1004,
    NODE_TYPE_ANALYSIS = 1006,
    NODE_TYPE_TIME_PITCH = 1007,
    NODE_TYPE_FREEZE = 1008,
    NODE_TYPE_SEND = 1009,
    NODE_TYPE_SOUNDTOUCH = 1010,
    NODE_TYPE_LATENCY = 1011,
    NODE_TYPE_PLUGIN_SLOT = 1012,
    NODE_TYPE_SINE_SYNTH = 1013,
    NODE_TYPE_INSTRUMENT_SLOT = 1014,
    NODE_TYPE_AUDIO_INPUT    = 1015,
    NODE_TYPE_MONITOR_SWITCH = 1016,
    NODE_TYPE_AUDIO_SEQUENCER = 1017,
    NODE_TYPE_MIDI_SEQUENCER = 1018,
    NODE_TYPE_AUDIO_TRACK     = 1019,
    NODE_TYPE_INSTRUMENT_TRACK= 1020
};

} // namespace DSP
